---
# Roles or collections we use in playbook

# ansible-galaxy collection install -r requirements.yml
# needs recent version of ansible-galaxy (4.3?)!

collections:
  - name: https://github.com/selfhostx/ansible.git
    type: git
  - name: ansible.posix
  - name: chocolatey.chocolatey
  - name: community.crypto
  - name: community.dns
  - name: community.general
  - name: community.libvirt
  - name: community.mysql
  - name: community.zabbix
  - name: inwx.collection
  - name: hifis.toolkit
