---
# FIXME: ALL=(ALL:ALL) or ALL=ALL ?
# yamllint disable rule:colons
- name: Manage group
  ansible.builtin.group:
    name:               '{{ item.groupname }}'
    gid:                '{{ item.gid         | d(omit) }}'
    state:              '{{ item.state       | d("present") }}'
    non_unique:         '{{ item.non_unique  | d(omit) }}'
    system:             '{{ item.system      | d(omit) }}'
# yamllint enable rule:colons

- name: Grant group sudo with password (when enabled)
  ansible.builtin.copy:
    content: '{{ item.groupname }} ALL=(ALL:ALL) {{ item.sudo_commands | default("ALL") }}'
    dest: /etc/sudoers.d/{{ item.sudofilename | default(item.groupname) }}
    owner: root
    group: root
    mode: 0640
    validate: 'visudo -cf %s'
  when:
    - item.sudo_pass is defined
    - item.sudo_pass|bool
    - not item.sudo_nopass|bool
    - item.state is undefined or (item.state is defined and not item.state == "absent")
  tags:
    - sudo

- name: Grant group sudo without password (when enabled)
  ansible.builtin.copy:
    content: '%{{ item.groupname }} ALL=(ALL:ALL) NOPASSWD:{{ item.sudo_commands | default("ALL") }}'
    dest: /etc/sudoers.d/{{ item.sudofilename | default(item.groupname) }}
    owner: root
    group: root
    mode: 0640
    validate: 'visudo -cf %s'
  when:
    - item.sudo_nopass is defined
    - item.sudo_nopass|bool
    - tem.state is undefined or (item.state is defined and not item.state == "absent")
  tags:
    - sudo
