---
- name: Install systemd-timesyncd (Redhat-family)
  ansible.builtin.dnf:
    name: "{{ baserole_ntp_systemd_timesyncd_package_name }}"
    state: present
  when:
    - baserole_ntp_systemd_timesyncd_package_name is defined
    - baserole_ntp_systemd_timesyncd_package_name | length > 0
    - ansible_os_family == "RedHat"
    - baserole_ntp_daemon == "systemd-timesyncd"
  notify: "Enable systemd-timesyncd"

- name: Install systemd-timesyncd (Debian-family)
  ansible.builtin.apt:
    name: "{{ baserole_ntp_systemd_timesyncd_package_name }}"
    state: present
    cache_valid_time: "{{ baserole_package_cache_valid_time }}"
  when:
    - baserole_ntp_systemd_timesyncd_package_name is defined
    - baserole_ntp_systemd_timesyncd_package_name | length > 0
    - ansible_os_family == "Debian"
    - baserole_ntp_daemon == "systemd-timesyncd"

- name: Configure systemd-timesyncd
  ansible.builtin.template:
    src: "{{ baserole_ntp_systemd_timesyncd_template }}"
    dest: "{{ baserole_ntp_systemd_timesyncd_config_target }}"
    owner: root
    group: root
    mode: '0644'
  notify: "Restart systemd-timesyncd"
  when:
    - baserole_ntp_daemon == "systemd-timesyncd"

- name: Start and Enable systemd-timesyncd
  ansible.builtin.systemd:
    name: "{{ baserole_dns_systemd_resolved_servicename }}"
    enabled: true
    masked: false
    state: started
  when:
    - baserole_ntp_daemon == "systemd-timesyncd"
