---
- name: Update package list and autoremove (Debian family)
  ansible.builtin.apt:
    upgrade: false
    update_cache: true
    autoremove: true
  when:
    - ansible_os_family == "Debian"

- name: Upgrade packages (debian family) # noqa: command-instead-of-module
  ansible.builtin.command: apt-get -y -o DPkg::options::="--force-confdef" -o DPkg::options::="--force-confold" upgrade
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: upgrade_output_debian
  when:
    - ansible_os_family == "Debian"

- name: Update Cache and Upgrade packages (RedHat family)
  ansible.builtin.dnf:
    name: '*'
    state: latest # noqa package-latest
    update_cache: true
  register: upgrade_output_redhat
  when:
    - ansible_os_family == "RedHat"

- name: Show upgrade stderr output (Debian)
  ansible.builtin.debug:
    msg: "{{ upgrade_output_debian.stderr_lines }}"
  when: upgrade_output_debian.stderr is defined and upgrade_output_debian.stderr | length > 0 and upgrade_output_debian.stderr != none

- name: Show upgrade stderr (Redhat)
  ansible.builtin.debug:
    msg: "{{ upgrade_output_redhat.stderr_lines }}"
  when: upgrade_output_redhat.stderr is defined and upgrade_output_redhat.stderr | length > 0 and upgrade_output_redhat.stderr != none
