
---
namespace: selfhostx
name: ansible
version: 1.6.2
readme: README.md
authors:
  - selfhostx
description: ansible-Collection for selfhosters (focussed on infrastructure and oss-apps)
license_file: LICENSE
tags:
  - selfhostx
repository: https://github.com/selfhostx/ansible.git
documentation: https://github.com/selfhostx/ansible.git
homepage: https://github.com/selfhostx/ansible
issues: https://github.com/selfhostx/ansible/issues
# FIXME
dependencies:
  # ansible.windows: "*"
  ansible.posix: "*"
  community.general: "*"
  community.mysql: "*"
  community.postgresql: "*"
