---
# defaults: https://github.com/selfhostx/ansible/blob/main/roles/nginx_common/defaults/main.yml

- name: Install nginx_ common (blank nginx)
  hosts: all
  roles:
    - selfhostx.ansible.nginx_common
