---
- name: Install vaultwarden
  hosts: vaultwarden.DOMAIN.TLD
  roles:
    # - { role: selfhostx.ansible.baserole, tags: baserole }
    - { role: geerlingguy.git, tags: git }
    - { role: geerlingguy.pip, tags: pip }
    - { role: geerlingguy.docker, tags: docker }
    - { role: selfhostx.certbot, tags: certbot }
    - { role: selfhostx.ansible.nginx_common, tags: nginx_common }
    - { role: selfhostx.ansible.vaultwarden, tags: vaultwarden }

  vars_files:
    - YOUR-vault.yml

  vars:
    # Token for the admin interface If not set, the admin panel is disabled
    # preferably use a long random string: openssl rand -base64 48
    # vaultwarden_admin_token: -> vault

    # when selfhostx.ansible.nginx_common is used:
    vaultwarden_nginx_use_nginx_common_snippet: true
    # letsencrypt:
    certbot_create_method: nginx
    # certbot_certs: -> host_vars
    certbot_certs:
      - domains:
        - "{{ vaultwarden_hostname }}"
    certbot_auto_renew_minute: 17
    certbot_auto_renew_hour: 3
    certbot_admin_email: mail@DOMAIN.TLD
    certbot_create_if_missing: true
    certbot_install_from_source: false
