---
# handlers file for vaultwarden

- name: Create service vaultwarden
  community.docker.docker_compose:
    project_src: "{{ vaultwarden_project_src }}"
    # build: true
    restarted: true
    state: present
  when:
    - not vaultwarden_user_docker_compose_cmd
  become: true

- name: Create service vaultwarden command
  ansible.builtin.command: "docker-compose up -d"
  args:
    chdir: "{{ vaultwarden_project_src }}"
  when:
    - vaultwarden_user_docker_compose_cmd
  become: true

- name: Build vaultwarden
  community.docker.docker_compose:
    project_src: "{{ vaultwarden_project_src }}"
    # build: true
    restarted: true
    state: present
  when:
    - not vaultwarden_user_docker_compose_cmd
  become: true

- name: Build vaultwarden command
  ansible.builtin.command: "docker-compose build"
  args:
    chdir: "{{ vaultwarden_project_src }}"
  when:
    - vaultwarden_user_docker_compose_cmd
  become: true

- name: Restart vaultwarden
  community.docker.docker_compose:
    project_src: "{{ vaultwarden_project_src }}"
    restarted: true
    state: present
  when:
    - not vaultwarden_user_docker_compose_cmd
  become: true

- name: Restart vaultwarden command
  ansible.builtin.shell: "docker-compose down && docker-compose up -d"
  args:
    chdir: "{{ vaultwarden_project_src }}"
  when:
    - vaultwarden_user_docker_compose_cmd
  become: true

- name: Reload nginx
  ansible.builtin.systemd:
    state: reloaded
    name: nginx
  become: true

- name: Restart nginx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
  become: true
