---
- name: Install nginx package
  ansible.builtin.package:
    name: nginx

- name: Remove default config (when enabled)
  ansible.builtin.file:
    path: "{{ rspamd_nginx_default_config }}"
    state: absent
  notify: Restart nginx
  when: rspamd_nginx_remove_default_config

- name: Ensure nginx config is present
  ansible.builtin.template:
    dest: "{{ rspamd_nginx_config_src_dir }}/{{ rspamd_nginx_config_filename }}"
    mode: "0644"
    src: "{{ rspamd_nginx_template }}"
  notify: Restart nginx

- name: Enable nginx config via symbolic link
  ansible.builtin.file:
    src: "{{ rspamd_nginx_config_src_dir }}/{{ rspamd_nginx_config_filename }}"
    dest: "{{ rspamd_nginx_config_dst_dir }}/{{ rspamd_nginx_config_filename }}"
    state: link
  notify: Restart nginx
