---
# source: https://github.com/securCom/ansible-role_repo-rspamd (BSD license)
- name: Add rspamd rpm key
  ansible.builtin.rpm_key:
    key: "{{ rspamd_repo_key }}"
  when: rspamd_enable_external_repo

- name: Add rspamd repository
  ansible.builtin.template:
    src: "repository-redhat.j2"
    dest: /etc/yum.repos.d/rspamd.repo
    owner: root
    group: root
    mode: '0644'
  when: rspamd_enable_external_repo

- name: Remove rspamd repository
  ansible.builtin.file:
    path: /etc/yum.repos.d/rspamd.repo
    state: absent
  when: not rspamd_enable_external_repo
