# source: https://github.com/MogiePete/zabbix-mdadm-template
---

- name: Include check-specific variables
  ansible.builtin.include_vars: "vars-mdraid.yml"

- name: Copy userparameters for mdraid
  ansible.builtin.template:
    src: "userparameter_mdraid.conf.j2"
    dest: "{{ zabbix_userparameter_mdraid_filename }}"
    owner: "{{ zabbix_user }}"
    group: "{{ zabbix_group }}"
    mode: '{{ zabbix_agent_conf_mode }}'
  notify: Restart zabbix-agent
