---
# FIXME template source
# needs command ss which is (usually) included in iproute2

- name: Include check-specific variables
  ansible.builtin.include_vars: "vars-tcpstats.yml"

- name: Create zabbix Include directory if it does not exist
  ansible.builtin.file:
    path: "{{ zabbix_agent_include_dir if not zabbix_agent2 else zabbix_agent2_include_dir }}"
    owner: "{{ zabbix_user }}"
    group: "{{ zabbix_group }}"
    state: directory
    mode: '0750'

- name: Copy script for tcpstats template
  ansible.builtin.copy:
    src: "files/{{ zabbix_userparameter_tcpstats_script_filename }}"
    dest: "{{ zabbix_userparameter_tcpstats_script_dest }}"
    owner: "{{ zabbix_user }}"
    group: "{{ zabbix_group }}"
    mode: '0750'

- name: Copy userparameters for tcpstats
  ansible.builtin.template:
    src: userparameter_tcpstats.conf.j2
    dest: "{{ zabbix_userparameter_tcpstats_dest }}"
    owner: "{{ zabbix_user }}"
    group: "{{ zabbix_group }}"
    mode: '0600'
  notify: Restart zabbix-agent
