---
# tasks file for uptime kuma

- name: Include OS-specific variables
  ansible.builtin.include_vars: "vars-{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Create user for uptime kuma
  ansible.builtin.user:
    name: "{{ uptimekuma_user }}"
    # group: "{{ uptimekuma_group }}"
    #groups: "{{ uptimekuma_memberof_groups | default(omit) }}"
    #append: true
    shell: "{{ uptimekuma_shell_bin }}"
    state: present
  become: true

- name: Import role for git
  ansible.builtin.import_role:
    name: "{{ uptimekuma_role_git_name }}"
  when: uptimekuma_role_git_import

- name: Install git
  ansible.builtin.package:
    name: git
    state: present
  when: not uptimekuma_role_git_import

- name: Install tar for nvm
  ansible.builtin.package:
    name: tar
    state: present
  when:
  - uptimekuma_use_nvm

- name: Import role for npm
  ansible.builtin.import_role:
    name: "{{ uptimekuma_role_npm_name }}"
    # robertdebock.npm
    #npm_apt_repositories:
    #  - "deb https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
    #  - "deb-src https://deb.nodesource.com/node_18.x {{ ansible_distribution_release }} main"
  become: true
  when:
  - uptimekuma_role_npm_import
  - not uptimekuma_use_nvm

- name: Import role for nvm
  ansible.builtin.import_role:
    name: "{{ uptimekuma_role_nvm_name }}"
  become: true
  become_user: "{{ uptimekuma_user }}"
  vars:
    # morgangraphics.ansible_role_nvm
    nvm_profile: "/home/{{ uptimekuma_user }}/{{ uptimekuma_shell_config }}"
    nodejs_version: "{{ uptimekuma_nvm_nodejs_version }}"
  when:
  - uptimekuma_use_nvm
  - uptimekuma_role_nvm_name is defined

- name: Create uptime kuma folder
  ansible.builtin.file:
    path: "{{ uptimekuma_install_dir }}"
    owner: "{{ uptimekuma_user }}"
    group: "{{ uptimekuma_group }}"
    mode: '0750'
    recurse: true
    state: directory
  become: true

- name: Get installed tag
  command: git describe --tags --abbrev=0
  args:
    chdir: "{{ uptimekuma_install_dir }}"
  become: true
  become_user: "{{ uptimekuma_user }}"
  register: git_tag_result
  failed_when: git_tag_result.rc != 0
  changed_when: false

- name: Debug installed tag
  debug:
    var: git_tag_result.stdout
  when: uptimekuma_debug|bool

- name: Get uptime kuma release info from github
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/louislam/uptime-kuma/releases/latest'
    return_content: true
  register: 'uptimekuma_version_github'
  when: uptimekuma_version is not defined or uptimekuma_version == "latest"

- name: Determine current uptime kuma release version
  ansible.builtin.set_fact:
    uptimekuma_version: "{{ uptimekuma_version_github['json']['tag_name'] }}"
  when: uptimekuma_version is not defined or uptimekuma_version == "latest"

- name: Debug uptimekuma_version fact
  debug:
    var: uptimekuma_version
  when:
    - uptimekuma_version is defined
    - uptimekuma_debug|bool

- name: Set 'uptimekuma_update' fact
  set_fact:
    uptimekuma_update: true
  when: git_tag_result.stdout != uptimekuma_version

- name: Debug 'uptimekuma_update' fact
  debug:
    var: uptimekuma_update
  when:
    - uptimekuma_update is defined
    - uptimekuma_debug|bool

- name: Set 'uptimekuma_install' fact
  set_fact:
    uptimekuma_install: true
  when: git_tag_result.stdout is not defined or git_tag_result.stdout == ''
      
- name: Debug 'uptimekuma_install' fact
  debug:
    var: uptimekuma_install
  when:
    - uptimekuma_install is defined
    - uptimekuma_debug|bool

- name: Clone uptime kuma repo
  ansible.builtin.git:
    clone: true
    dest: "{{ uptimekuma_install_dir }}"
    force: true
    repo: "{{ uptimekuma_git_repo_url }}"
    update: false
    version: '{{ uptimekuma_version | default(omit) }}'
  become: true
  become_user: "{{ uptimekuma_user }}"
  register: uptimekuma_cloned
  when:
    - uptimekuma_install is defined
    - uptimekuma_install|bool
    
- name: update uptime kuma repo
  ansible.builtin.git:
    clone: false
    dest: "{{ uptimekuma_install_dir }}"
    force: true
    repo: "{{ uptimekuma_git_repo_url }}"
    update: true
    version: '{{ uptimekuma_version | default(omit) }}'
  become: true
  become_user: "{{ uptimekuma_user }}"
  register: uptimekuma_updated
  when:
    - uptimekuma_update is defined
    - uptimekuma_update|bool

- name: Install uptime kuma
  ansible.builtin.shell: bash -ilc 'npm run setup'
  #args:
 #   executable: "{{ uptimekuma_shell_bin }}"
  become: true
  become_user: "{{ uptimekuma_user }}"
  args:
    chdir: "{{ uptimekuma_install_dir }}"
  when: 
    - uptimekuma_cloned.changed
    - uptimekuma_install|bool
    
- name: update uptime kuma
  ansible.builtin.shell: 
    cmd: "{{ item }}"
  #args:
 #   executable: "{{ uptimekuma_shell_bin }}"
  become: true
  become_user: "{{ uptimekuma_user }}"
  args:
    chdir: "{{ uptimekuma_install_dir }}"
  loop:
    - bash -ilc 'npm install --production'
    - bash -ilc 'npm run download-dist'
  when: 
    - uptimekuma_updated.changed
    - uptimekuma_update|bool
  notify: Restart uptime kuma

- name: Create uptime kuma start skript
  ansible.builtin.template:
    src: "start.sh.j2"
    dest: "{{ uptimekuma_install_dir }}/start.sh"
    owner: "{{ uptimekuma_user }}"
    group: "{{ uptimekuma_group }}"
    mode: '0750'
  become: true
  notify: Restart uptime kuma

- name: Create systemd service file for uptime kuma
  ansible.builtin.template:
    src: "{{ uptimekuma_service_file_template }}"
    dest: "{{ uptimekuma_service_file_target }}"
  become: true
  notify: Reload systemd units

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable and start uptime kuma as systemd unit
  ansible.builtin.systemd:
    name: "{{ uptimekuma_service_name }}"
    state: started
    enabled: true
  become: true 

- include_tasks: nginx.yml
  when: uptimekuma_nginx_deploy_reverseconfig
