---
# tasks file

- name: Install requirements
  ansible.builtin.include_tasks:
    file: "install_requirements.yml"
    apply:
      tags:
        - requirements
  tags: requirements
  when:
    - compute_instance_install_requirements or compute_instance_install_pip_enable

# cloud-init templates
- name: Include cloudinit-template-*.yml (create cloud-init templates when requested)
  ansible.builtin.include_tasks:
    file: "cloudinit-template-{{ compute_instance_virtualization_provider }}.yml"
    apply:
      tags:
        - cloudinit_image_create
  tags: cloudinit_image_create
  when:
    - cloudinit_image_create_enable

# common tasks
- name: Include common.yml
  ansible.builtin.include_tasks:
    file: "common.yml"
    apply:
      tags:
        - always
  tags: always

# IPAM solutions
- name: Include ipam-*.yml
  ansible.builtin.include_tasks:
    file: "ipam-{{ compute_instance_ipam_provider }}.yml"
    apply:
      tags:
        - compute
  tags: compute
  when:
    - compute_instance_ipam_provider is defined

# Debug
- name: Print Debug info
  when:
    - compute_instance_debug_mode_enable
    - compute_instance_virtualization_provider == "proxmox"
  block:

    - name: Show used IPv4 (proxmox)
      ansible.builtin.debug:
        msg: "assigned ipv4: {{ proxmox_network_ip_v4_prefixed }}"
      when:
        - compute_instance_debug_mode_enable
        - proxmox_network_ip_v4_prefixed is defined
        - compute_instance_virtualization_provider == "proxmox"

    - name: Show used IPv6 (proxmox)
      ansible.builtin.debug:
        msg: "assigned ipv6: {{ proxmox_network_ip_v6_prefixed }}"
      when:
        - compute_instance_debug_mode_enable
        - proxmox_network_ip_v6_prefixed is defined
        - compute_instance_virtualization_provider == "proxmox"

    - name: Show IPv4 gateway (proxmox)
      ansible.builtin.debug:
        msg: "{{ proxmox_network_gateway_v4 }}"
      when:
        - compute_instance_debug_mode_enable
        - proxmox_network_gateway_v4 is defined
        - compute_instance_virtualization_provider == "proxmox"

    - name: Show IPv6 gateway (proxmox)
      ansible.builtin.debug:
        msg: "{{ proxmox_network_gateway_v6 }}"
      when:
        - compute_instance_debug_mode_enable
        - proxmox_network_gateway_v6 is defined
        - compute_instance_virtualization_provider == "proxmox"

# instances
- name: Include compute-*.yml
  ansible.builtin.include_tasks:
    file: "compute-{{ compute_instance_virtualization_provider }}.yml"
    apply:
      tags:
        - dns
  tags: compute
  when:
    - compute_instance_virtualization_provider is defined

# DNS
- name: Include dns-*.yml
  ansible.builtin.include_tasks:
    file: "dns-{{ compute_instance_dns_provider }}.yml"
    apply:
      tags:
        - dns
  tags: dns
  when:
    - compute_instance_dns_create_records_enable
    - compute_instance_dns_provider is defined
