---
# Example playbook for hifis.toolkit.unattended_upgrades
- hosts: all
  roles:
    - { role: hifis.toolkit.unattended_upgrades, tags: unattended_upgrades }

  # OR just for virtual systems:
  tasks:
    - name: Classify hosts (virtual or bare metal)
      ansible.builtin.group_by:
        key: machine_is_{{ "virtual" if ansible_facts['virtualization_role'] == "guest" else "metal" }}
      changed_when: false

    - name: Include unattended-upgrades for virtual systems
      ansible.builtin.include_role:
        name: hifis.toolkit.unattended_upgrades
      when:
      - "'machine_is_virtual' in group_names"
      - ansible_os_family == "Debian"

  vars:
    unattended_mail: 'root'  # needs mailx on system!
    unattended_mail_report: "only-on-error"
    # unattended_remove_unused_kernel_packages: true
    unattended_syslog_enable: true
    unattended_automatic_reboot: true
    unattended_automatic_reboot_time: "03:00"
    unattended_remove_unused_dependencies: true
